package com.vladsch.kotlin.jdbc

import java.sql.CallableStatement
import java.sql.PreparedStatement
import java.sql.ResultSet
import javax.json.JsonArray
import javax.json.JsonObject

interface Session : AutoCloseable {
    val connection: Connection
    val autoGeneratedKeys: List<String>
    val identifierQuoteString:String

    fun use(block: (Session) -> Unit)

    fun prepare(query: SqlQuery, returnGeneratedKeys: Boolean = false): PreparedStatement
    fun prepare(query: SqlCall): CallableStatement
    fun prepare(query: SqlQueryBase<*>): PreparedStatement

    fun <A> query(query: SqlQueryBase<*>, consumer: (ResultSet) -> A): A

    fun <A> execute(query: SqlQueryBase<*>, consumer: (PreparedStatement) -> A): A?
    fun <A> execute(query: SqlCall, consumer: (CallableStatement) -> A): A?

    fun <A> executeWithKeys(query: SqlQuery, consumer: (PreparedStatement) -> A): A?
    fun <A> updateWithKeys(query: SqlQuery, consumer: (PreparedStatement) -> A): A?
    fun <A> update(query: SqlQueryBase<*>, consumer: (PreparedStatement) -> A): A?
    fun <A> list(query: SqlQueryBase<*>, extractor: (Row) -> A): List<A>
    fun jsonArray(query: SqlQueryBase<*>, extractor: (Row) -> JsonObject): JsonArray
    fun count(query: SqlQueryBase<*>): Int
    fun <A> first(query: SqlQueryBase<*>, extractor: (Row) -> A): A?
    fun <K, A> hashMap(query: SqlQueryBase<*>, keyExtractor: (Row) -> K, extractor: (Row) -> A): Map<K, A>
    fun jsonObject(query: SqlQueryBase<*>, keyExtractor: (Row) -> String, extractor: (Row) -> JsonObject): JsonObject
    fun forEach(query: SqlQueryBase<*>, operator: (Row) -> Unit)

    @Deprecated(message = "Use executeCall(query: SqlCall, stmtProc: (results: SqlCallResults) -> Unit) instead", replaceWith = ReplaceWith("executeCall"))
    fun forEach(query: SqlCall, stmtProc: (stmt: CallableStatement) -> Unit, operator: (rs: ResultSet, index: Int) -> Unit)
    fun executeCall(query: SqlCall, stmtProc: (results: SqlCallResults) -> Unit)

    fun execute(query: SqlQueryBase<*>): Boolean
    fun update(query: SqlQueryBase<*>): Int
    fun updateGetLongId(query: SqlQuery): Long?
    fun updateGetId(query: SqlQuery): Int?
    fun <A> updateGetKey(query: SqlQuery, extractor: (Row) -> A): A?
    fun updateGetLongIds(query: SqlQuery): List<Long>?
    fun updateGetIds(query: SqlQuery): List<Int>?
    fun <A> updateGetKeys(query: SqlQuery, extractor: (Row) -> A): List<A>?
    fun <A> transaction(operation: (Transaction) -> A): A

    override fun close()
}
