package com.vladsch.kotlin.jdbc

import java.sql.Savepoint

class TransactionImpl(
    connection: Connection,
    autoGeneratedKeys: List<String> = listOf()
) : SessionImpl(connection, autoGeneratedKeys), Transaction {

    override fun commit() {
        connection.commit()
    }

    override fun begin() {
        connection.begin()
    }

    override fun rollback() {
        connection.rollback()
    }

    override fun setSavepoint(): Savepoint {
        return connection.setSavepoint()
    }

    override fun setSavepoint(name: String): Savepoint {
        return connection.setSavepoint(name)
    }

    override fun rollback(savepoint: Savepoint) {
        connection.rollback(savepoint)
    }

    override fun releaseSavepoint(savepoint: Savepoint) {
        connection.releaseSavepoint(savepoint)
    }
}
